#
# Copyright (c) 2022 by Kristoffer Paulsson <kristoffer.paulsson@talenten.se>.
#
# Permission to use, copy, modify, and/or distribute this software for any purpose with
# or without fee is hereby granted, provided that the above copyright notice and this
# permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO
# THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
# IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#     https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
#
# Contributors:
#     Kristoffer Paulsson - initial implementation
#
"""Class for dealing with extended unicode, nothing else."""
from greektextify.text.alphabet import GreekAlphabet
from greektextify.text.diacritic import GreekDiacritic


class GreekExtended:
    SMALL_ALPHA_PSILI = '\u1F00'
    SMALL_ALPHA_DASIA = '\u1F01'
    SMALL_ALPHA_PSILI_VARIA = '\u1F02'
    SMALL_ALPHA_DASIA_VARIA = '\u1F03'
    SMALL_ALPHA_PSILI_OXIA = '\u1F04'
    SMALL_ALPHA_DASIA_OXIA = '\u1F05'
    SMALL_ALPHA_PSILI_PERISPOMENI = '\u1F06'
    SMALL_ALPHA_DASIA_PERISPOMENI = '\u1F07'
    CAPITAL_ALPHA_PSILI = '\u1F08'
    CAPITAL_ALPHA_DASIA = '\u1F09'
    CAPITAL_ALPHA_PSILI_VARIA = '\u1F0A'
    CAPITAL_ALPHA_DASIA_VARIA = '\u1F0B'
    CAPITAL_ALPHA_PSILI_OXIA = '\u1F0C'
    CAPITAL_ALPHA_DASIA_OXIA = '\u1F0D'
    CAPITAL_ALPHA_PSILI_PERISPOMENI = '\u1F0E'
    CAPITAL_ALPHA_DASIA_PERISPOMENI = '\u1F0F'
    SMALL_EPSILON_PSILI = '\u1F10'
    SMALL_EPSILON_DASIA = '\u1F11'
    SMALL_EPSILON_PSILI_VARIA = '\u1F12'
    SMALL_EPSILON_DASIA_VARIA = '\u1F13'
    SMALL_EPSILON_PSILI_OXIA = '\u1F14'
    SMALL_EPSILON_DASIA_OXIA = '\u1F15'
    CAPITAL_EPSILON_PSILI = '\u1F18'
    CAPITAL_EPSILON_DASIA = '\u1F19'
    CAPITAL_EPSILON_PSILI_VARIA = '\u1F1A'
    CAPITAL_EPSILON_DASIA_VARIA = '\u1F1B'
    CAPITAL_EPSILON_PSILI_OXIA = '\u1F1C'
    CAPITAL_EPSILON_DASIA_OXIA = '\u1F1D'
    SMALL_ETA_PSILI = '\u1F20'
    SMALL_ETA_DASIA = '\u1F21'
    SMALL_ETA_PSILI_VARIA = '\u1F22'
    SMALL_ETA_DASIA_VARIA = '\u1F23'
    SMALL_ETA_PSILI_OXIA = '\u1F24'
    SMALL_ETA_DASIA_OXIA = '\u1F25'
    SMALL_ETA_PSILI_PERISPOMENI = '\u1F26'
    SMALL_ETA_DASIA_PERISPOMENI = '\u1F27'
    CAPITAL_ETA_PSILI = '\u1F28'
    CAPITAL_ETA_DASIA = '\u1F29'
    CAPITAL_ETA_PSILI_VARIA = '\u1F2A'
    CAPITAL_ETA_DASIA_VARIA = '\u1F2B'
    CAPITAL_ETA_PSILI_OXIA = '\u1F2C'
    CAPITAL_ETA_DASIA_OXIA = '\u1F2D'
    CAPITAL_ETA_PSILI_PERISPOMENI = '\u1F2E'
    CAPITAL_ETA_DASIA_PERISPOMENI = '\u1F2F'
    SMALL_IOTA_PSILI = '\u1F30'
    SMALL_IOTA_DASIA = '\u1F31'
    SMALL_IOTA_PSILI_VARIA = '\u1F32'
    SMALL_IOTA_DASIA_VARIA = '\u1F33'
    SMALL_IOTA_PSILI_OXIA = '\u1F34'
    SMALL_IOTA_DASIA_OXIA = '\u1F35'
    SMALL_IOTA_PSILI_PERISPOMENI = '\u1F36'
    SMALL_IOTA_DASIA_PERISPOMENI = '\u1F37'
    CAPITAL_IOTA_PSILI = '\u1F38'
    CAPITAL_IOTA_DASIA = '\u1F39'
    CAPITAL_IOTA_PSILI_VARIA = '\u1F3A'
    CAPITAL_IOTA_DASIA_VARIA = '\u1F3B'
    CAPITAL_IOTA_PSILI_OXIA = '\u1F3C'
    CAPITAL_IOTA_DASIA_OXIA = '\u1F3D'
    CAPITAL_IOTA_PSILI_PERISPOMENI = '\u1F3E'
    CAPITAL_IOTA_DASIA_PERISPOMENI = '\u1F3F'
    SMALL_OMICRON_PSILI = '\u1F40'
    SMALL_OMICRON_DASIA = '\u1F41'
    SMALL_OMICRON_PSILI_VARIA = '\u1F42'
    SMALL_OMICRON_DASIA_VARIA = '\u1F43'
    SMALL_OMICRON_PSILI_OXIA = '\u1F44'
    SMALL_OMICRON_DASIA_OXIA = '\u1F45'
    CAPITAL_OMICRON_PSILI = '\u1F48'
    CAPITAL_OMICRON_DASIA = '\u1F49'
    CAPITAL_OMICRON_PSILI_VARIA = '\u1F4A'
    CAPITAL_OMICRON_DASIA_VARIA = '\u1F4B'
    CAPITAL_OMICRON_PSILI_OXIA = '\u1F4C'
    CAPITAL_OMICRON_DASIA_OXIA = '\u1F4D'
    SMALL_UPSILON_PSILI = '\u1F50'
    SMALL_UPSILON_DASIA = '\u1F51'
    SMALL_UPSILON_PSILI_VARIA = '\u1F52'
    SMALL_UPSILON_DASIA_VARIA = '\u1F53'
    SMALL_UPSILON_PSILI_OXIA = '\u1F54'
    SMALL_UPSILON_DASIA_OXIA = '\u1F55'
    SMALL_UPSILON_PSILI_PERISPOMENI = '\u1F56'
    SMALL_UPSILON_DASIA_PERISPOMENI = '\u1F57'
    CAPITAL_UPSILON_DASIA = '\u1F59'
    CAPITAL_UPSILON_DASIA_VARIA = '\u1F5B'
    CAPITAL_UPSILON_DASIA_OXIA = '\u1F5D'
    CAPITAL_UPSILON_DASIA_PERISPOMENI = '\u1F5F'
    SMALL_OMEGA_PSILI = '\u1F60'
    SMALL_OMEGA_DASIA = '\u1F61'
    SMALL_OMEGA_PSILI_VARIA = '\u1F62'
    SMALL_OMEGA_DASIA_VARIA = '\u1F63'
    SMALL_OMEGA_PSILI_OXIA = '\u1F64'
    SMALL_OMEGA_DASIA_OXIA = '\u1F65'
    SMALL_OMEGA_PSILI_PERISPOMENI = '\u1F66'
    SMALL_OMEGA_DASIA_PERISPOMENI = '\u1F67'
    CAPITAL_OMEGA_PSILI = '\u1F68'
    CAPITAL_OMEGA_DASIA = '\u1F69'
    CAPITAL_OMEGA_PSILI_VARIA = '\u1F6A'
    CAPITAL_OMEGA_DASIA_VARIA = '\u1F6B'
    CAPITAL_OMEGA_PSILI_OXIA = '\u1F6C'
    CAPITAL_OMEGA_DASIA_OXIA = '\u1F6D'
    CAPITAL_OMEGA_PSILI_PERISPOMENI = '\u1F6E'
    CAPITAL_OMEGA_DASIA_PERISPOMENI = '\u1F6F'
    SMALL_ALPHA_VARIA = '\u1F70'
    SMALL_ALPHA_OXIA = '\u1F71'
    SMALL_EPSILON_VARIA = '\u1F72'
    SMALL_EPSILON_OXIA = '\u1F73'
    SMALL_ETA_VARIA = '\u1F74'
    SMALL_ETA_OXIA = '\u1F75'
    SMALL_IOTA_VARIA = '\u1F76'
    SMALL_IOTA_OXIA = '\u1F77'
    SMALL_OMICRON_VARIA = '\u1F78'
    SMALL_OMICRON_OXIA = '\u1F79'
    SMALL_UPSILON_VARIA = '\u1F7A'
    SMALL_UPSILON_OXIA = '\u1F7B'
    SMALL_OMEGA_VARIA = '\u1F7C'
    SMALL_OMEGA_OXIA = '\u1F7D'
    SMALL_ALPHA_PSILI_YPOGEGRAMMENI = '\u1F80'
    SMALL_ALPHA_DASIA_YPOGEGRAMMENI = '\u1F81'
    SMALL_ALPHA_PSILI_VARIA_YPOGEGRAMMENI = '\u1F82'
    SMALL_ALPHA_DASIA_VARIA_YPOGEGRAMMENI = '\u1F83'
    SMALL_ALPHA_PSILI_OXIA_YPOGEGRAMMENI = '\u1F84'
    SMALL_ALPHA_DASIA_OXIA_YPOGEGRAMMENI = '\u1F85'
    SMALL_ALPHA_PSILI_PERISPOMENI_YPOGEGRAMMENI = '\u1F86'
    SMALL_ALPHA_DASIA_PERISPOMENI_YPOGEGRAMMENI = '\u1F87'
    CAPITAL_ALPHA_PSILI_PROSGEGRAMMENI = '\u1F88'
    CAPITAL_ALPHA_DASIA_PROSGEGRAMMENI = '\u1F89'
    CAPITAL_ALPHA_PSILI_VARIA_PROSGEGRAMMENI = '\u1F8A'
    CAPITAL_ALPHA_DASIA_VARIA_PROSGEGRAMMENI = '\u1F8B'
    CAPITAL_ALPHA_PSILI_OXIA_PROSGEGRAMMENI = '\u1F8C'
    CAPITAL_ALPHA_DASIA_OXIA_PROSGEGRAMMENI = '\u1F8D'
    CAPITAL_ALPHA_PSILI_PERISPOMENI_PROSGEGRAMMENI = '\u1F8E'
    CAPITAL_ALPHA_DASIA_PERISPOMENI_PROSGEGRAMMENI = '\u1F8F'
    SMALL_ETA_PSILI_YPOGEGRAMMENI = '\u1F90'
    SMALL_ETA_DASIA_YPOGEGRAMMENI = '\u1F91'
    SMALL_ETA_PSILI_VARIA_YPOGEGRAMMENI = '\u1F92'
    SMALL_ETA_DASIA_VARIA_YPOGEGRAMMENI = '\u1F93'
    SMALL_ETA_PSILI_OXIA_YPOGEGRAMMENI = '\u1F94'
    SMALL_ETA_DASIA_OXIA_YPOGEGRAMMENI = '\u1F95'
    SMALL_ETA_PSILI_PERISPOMENI_YPOGEGRAMMENI = '\u1F96'
    SMALL_ETA_DASIA_PERISPOMENI_YPOGEGRAMMENI = '\u1F97'
    CAPITAL_ETA_PSILI_PROSGEGRAMMENI = '\u1F98'
    CAPITAL_ETA_DASIA_PROSGEGRAMMENI = '\u1F99'
    CAPITAL_ETA_PSILI_VARIA_PROSGEGRAMMENI = '\u1F9A'
    CAPITAL_ETA_DASIA_VARIA_PROSGEGRAMMENI = '\u1F9B'
    CAPITAL_ETA_PSILI_OXIA_PROSGEGRAMMENI = '\u1F9C'
    CAPITAL_ETA_DASIA_OXIA_PROSGEGRAMMENI = '\u1F9D'
    CAPITAL_ETA_PSILI_PERISPOMENI_PROSGEGRAMMENI = '\u1F9E'
    CAPITAL_ETA_DASIA_PERISPOMENI_PROSGEGRAMMENI = '\u1F9F'
    SMALL_OMEGA_PSILI_YPOGEGRAMMENI = '\u1FA0'
    SMALL_OMEGA_DASIA_YPOGEGRAMMENI = '\u1FA1'
    SMALL_OMEGA_PSILI_VARIA_YPOGEGRAMMENI = '\u1FA2'
    SMALL_OMEGA_DASIA_VARIA_YPOGEGRAMMENI = '\u1FA3'
    SMALL_OMEGA_PSILI_OXIA_YPOGEGRAMMENI = '\u1FA4'
    SMALL_OMEGA_DASIA_OXIA_YPOGEGRAMMENI = '\u1FA5'
    SMALL_OMEGA_PSILI_PERISPOMENI_YPOGEGRAMMENI = '\u1FA6'
    SMALL_OMEGA_DASIA_PERISPOMENI_YPOGEGRAMMENI = '\u1FA7'
    CAPITAL_OMEGA_PSILI_PROSGEGRAMMENI = '\u1FA8'
    CAPITAL_OMEGA_DASIA_PROSGEGRAMMENI = '\u1FA9'
    CAPITAL_OMEGA_PSILI_VARIA_PROSGEGRAMMENI = '\u1FAA'
    CAPITAL_OMEGA_DASIA_VARIA_PROSGEGRAMMENI = '\u1FAB'
    CAPITAL_OMEGA_PSILI_OXIA_PROSGEGRAMMENI = '\u1FAC'
    CAPITAL_OMEGA_DASIA_OXIA_PROSGEGRAMMENI = '\u1FAD'
    CAPITAL_OMEGA_PSILI_PERISPOMENI_PROSGEGRAMMENI = '\u1FAE'
    CAPITAL_OMEGA_DASIA_PERISPOMENI_PROSGEGRAMMENI = '\u1FAF'
    SMALL_ALPHA_VRACHY = '\u1FB0'
    SMALL_ALPHA_MACRON = '\u1FB1'
    SMALL_ALPHA_VARIA_YPOGEGRAMMENI = '\u1FB2'
    SMALL_ALPHA_YPOGEGRAMMENI = '\u1FB3'
    SMALL_ALPHA_OXIA_YPOGEGRAMMENI = '\u1FB4'
    SMALL_ALPHA_PERISPOMENI = '\u1FB6'
    SMALL_ALPHA_PERISPOMENI_YPOGEGRAMMENI = '\u1FB7'
    CAPITAL_ALPHA_VRACHY = '\u1FB8'
    CAPITAL_ALPHA_MACRON = '\u1FB9'
    CAPITAL_ALPHA_VARIA = '\u1FBA'
    CAPITAL_ALPHA_OXIA = '\u1FBB'
    CAPITAL_ALPHA_PROSGEGRAMMENI = '\u1FBC'
    PROSGEGRAMMENI = '\u1FBE'
    DIALYTIKA_PERISPOMENI = '\u1FC1'
    SMALL_ETA_VARIA_YPOGEGRAMMENI = '\u1FC2'
    SMALL_ETA_YPOGEGRAMMENI = '\u1FC3'
    SMALL_ETA_OXIA_YPOGEGRAMMENI = '\u1FC4'
    SMALL_ETA_PERISPOMENI = '\u1FC6'
    SMALL_ETA_PERISPOMENI_YPOGEGRAMMENI = '\u1FC7'
    CAPITAL_EPSILON_VARIA = '\u1FC8'
    CAPITAL_EPSILON_OXIA = '\u1FC9'
    CAPITAL_ETA_VARIA = '\u1FCA'
    CAPITAL_ETA_OXIA = '\u1FCB'
    CAPITAL_ETA_PROSGEGRAMMENI = '\u1FCC'
    PSILI_VARIA = '\u1FCD'
    PSILI_OXIA = '\u1FCE'
    PSILI_PERISPOMENI = '\u1FCF'
    SMALL_IOTA_VRACHY = '\u1FD0'
    SMALL_IOTA_MACRON = '\u1FD1'
    SMALL_IOTA_DIALYTIKA_VARIA = '\u1FD2'
    SMALL_IOTA_DIALYTIKA_OXIA = '\u1FD3'
    SMALL_IOTA_PERISPOMENI = '\u1FD6'
    SMALL_IOTA_DIALYTIKA_PERISPOMENI = '\u1FD7'
    CAPITAL_IOTA_VRACHY = '\u1FD8'
    CAPITAL_IOTA_MACRON = '\u1FD9'
    CAPITAL_IOTA_VARIA = '\u1FDA'
    CAPITAL_IOTA_OXIA = '\u1FDB'
    DASIA_VARIA = '\u1FDD'
    DASIA_OXIA = '\u1FDE'
    DASIA_PERISPOMENI = '\u1FDF'
    SMALL_UPSILON_VRACHY = '\u1FE0'
    SMALL_UPSILON_MACRON = '\u1FE1'
    SMALL_UPSILON_DIALYTIKA_VARIA = '\u1FE2'
    SMALL_UPSILON_DIALYTIKA_OXIA = '\u1FE3'
    SMALL_RHO_PSILI = '\u1FE4'
    SMALL_RHO_DASIA = '\u1FE5'
    SMALL_UPSILON_PERISPOMENI = '\u1FE6'
    SMALL_UPSILON_DIALYTIKA_PERISPOMENI = '\u1FE7'
    CAPITAL_UPSILON_VRACHY = '\u1FE8'
    CAPITAL_UPSILON_MACRON = '\u1FE9'
    CAPITAL_UPSILON_VARIA = '\u1FEA'
    CAPITAL_UPSILON_OXIA = '\u1FEB'
    CAPITAL_RHO_DASIA = '\u1FEC'
    DIALYTIKA_VARIA = '\u1FED'
    DIALYTIKA_OXIA = '\u1FEE'
    VARIA = '\u1FEF'
    SMALL_OMEGA_VARIA_YPOGEGRAMMENI = '\u1FF2'
    SMALL_OMEGA_YPOGEGRAMMENI = '\u1FF3'
    SMALL_OMEGA_OXIA_YPOGEGRAMMENI = '\u1FF4'
    SMALL_OMEGA_PERISPOMENI = '\u1FF6'
    SMALL_OMEGA_PERISPOMENI_YPOGEGRAMMENI = '\u1FF7'
    CAPITAL_OMICRON_VARIA = '\u1FF8'
    CAPITAL_OMICRON_OXIA = '\u1FF9'
    CAPITAL_OMEGA_VARIA = '\u1FFA'
    CAPITAL_OMEGA_OXIA = '\u1FFB'
    CAPITAL_OMEGA_PROSGEGRAMMENI = '\u1FFC'
    OXIA = '\u1FFD'
    KORONIS = '\u1FBD'
    PSILI = '\u1FBF'
    PERISPOMENI = '\u1FC0'
    DASIA = '\u1FFE'

    EXPANDABLE_LETTERS = {
        SMALL_ALPHA_PSILI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI,
        SMALL_ALPHA_DASIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA,
        SMALL_ALPHA_PSILI_VARIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_ALPHA_DASIA_VARIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_ALPHA_PSILI_OXIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_ALPHA_DASIA_OXIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_ALPHA_PSILI_PERISPOMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_ALPHA_DASIA_PERISPOMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_ALPHA_PSILI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI,
        CAPITAL_ALPHA_DASIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_ALPHA_PSILI_VARIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_ALPHA_DASIA_VARIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_ALPHA_PSILI_OXIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ALPHA_DASIA_OXIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ALPHA_PSILI_PERISPOMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_ALPHA_DASIA_PERISPOMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_EPSILON_PSILI: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_PSILI,
        SMALL_EPSILON_DASIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_DASIA,
        SMALL_EPSILON_PSILI_VARIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_EPSILON_DASIA_VARIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_EPSILON_PSILI_OXIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_EPSILON_DASIA_OXIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_EPSILON_PSILI: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_PSILI,
        CAPITAL_EPSILON_DASIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_EPSILON_PSILI_VARIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_EPSILON_DASIA_VARIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_EPSILON_PSILI_OXIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_EPSILON_DASIA_OXIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_ETA_PSILI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI,
        SMALL_ETA_DASIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA,
        SMALL_ETA_PSILI_VARIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_ETA_DASIA_VARIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_ETA_PSILI_OXIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_ETA_DASIA_OXIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_ETA_PSILI_PERISPOMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_ETA_DASIA_PERISPOMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_ETA_PSILI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI,
        CAPITAL_ETA_DASIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_ETA_PSILI_VARIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_ETA_DASIA_VARIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_ETA_PSILI_OXIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ETA_DASIA_OXIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ETA_PSILI_PERISPOMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_ETA_DASIA_PERISPOMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_IOTA_PSILI: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_PSILI,
        SMALL_IOTA_DASIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DASIA,
        SMALL_IOTA_PSILI_VARIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_IOTA_DASIA_VARIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_IOTA_PSILI_OXIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_IOTA_DASIA_OXIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_IOTA_PSILI_PERISPOMENI: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_IOTA_DASIA_PERISPOMENI: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_IOTA_PSILI: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_PSILI,
        CAPITAL_IOTA_DASIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_IOTA_PSILI_VARIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_IOTA_DASIA_VARIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_IOTA_PSILI_OXIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_IOTA_DASIA_OXIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_IOTA_PSILI_PERISPOMENI: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_IOTA_DASIA_PERISPOMENI: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_OMICRON_PSILI: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_PSILI,
        SMALL_OMICRON_DASIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_DASIA,
        SMALL_OMICRON_PSILI_VARIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_OMICRON_DASIA_VARIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_OMICRON_PSILI_OXIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_OMICRON_DASIA_OXIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_OMICRON_PSILI: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_PSILI,
        CAPITAL_OMICRON_DASIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_OMICRON_PSILI_VARIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_OMICRON_DASIA_VARIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_OMICRON_PSILI_OXIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_OMICRON_DASIA_OXIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_UPSILON_PSILI: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_PSILI,
        SMALL_UPSILON_DASIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DASIA,
        SMALL_UPSILON_PSILI_VARIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_UPSILON_DASIA_VARIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_UPSILON_PSILI_OXIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_UPSILON_DASIA_OXIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_UPSILON_PSILI_PERISPOMENI: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_UPSILON_DASIA_PERISPOMENI: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_UPSILON_DASIA: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_UPSILON_DASIA_VARIA: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_UPSILON_DASIA_OXIA: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_UPSILON_DASIA_PERISPOMENI: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_OMEGA_PSILI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI,
        SMALL_OMEGA_DASIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA,
        SMALL_OMEGA_PSILI_VARIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        SMALL_OMEGA_DASIA_VARIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        SMALL_OMEGA_PSILI_OXIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        SMALL_OMEGA_DASIA_OXIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        SMALL_OMEGA_PSILI_PERISPOMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_OMEGA_DASIA_PERISPOMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_OMEGA_PSILI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI,
        CAPITAL_OMEGA_DASIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA,
        CAPITAL_OMEGA_PSILI_VARIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_OMEGA_DASIA_VARIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_OMEGA_PSILI_OXIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_OMEGA_DASIA_OXIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_OMEGA_PSILI_PERISPOMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_OMEGA_DASIA_PERISPOMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_ALPHA_VARIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_VARIA,
        SMALL_ALPHA_OXIA: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_OXIA,
        SMALL_EPSILON_VARIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_VARIA,
        SMALL_EPSILON_OXIA: GreekAlphabet.LOWER_EPSILON + GreekDiacritic.COMBINING_OXIA,
        SMALL_ETA_VARIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_VARIA,
        SMALL_ETA_OXIA: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_OXIA,
        SMALL_IOTA_VARIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_VARIA,
        SMALL_IOTA_OXIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_OXIA,
        SMALL_OMICRON_VARIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_VARIA,
        SMALL_OMICRON_OXIA: GreekAlphabet.LOWER_OMICRON + GreekDiacritic.COMBINING_OXIA,
        SMALL_UPSILON_VARIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_VARIA,
        SMALL_UPSILON_OXIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_OXIA,
        SMALL_OMEGA_VARIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_VARIA,
        SMALL_OMEGA_OXIA: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_OXIA,
        SMALL_ALPHA_PSILI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_DASIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_PSILI_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_DASIA_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_PSILI_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_DASIA_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_PSILI_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_DASIA_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        CAPITAL_ALPHA_PSILI_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_DASIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_PSILI_VARIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_DASIA_VARIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_PSILI_OXIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_DASIA_OXIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_PSILI_PERISPOMENI_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ALPHA_DASIA_PERISPOMENI_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        SMALL_ETA_PSILI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_DASIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_PSILI_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_DASIA_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_PSILI_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_DASIA_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_PSILI_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_DASIA_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        CAPITAL_ETA_PSILI_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_DASIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_PSILI_VARIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_DASIA_VARIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_PSILI_OXIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_DASIA_OXIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_PSILI_PERISPOMENI_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_ETA_DASIA_PERISPOMENI_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        SMALL_OMEGA_PSILI_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_DASIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_PSILI_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_DASIA_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_PSILI_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_DASIA_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_PSILI_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_DASIA_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        CAPITAL_OMEGA_PSILI_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_DASIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_PSILI_VARIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_DASIA_VARIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_PSILI_OXIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_DASIA_OXIA_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_PSILI_PERISPOMENI_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        CAPITAL_OMEGA_DASIA_PERISPOMENI_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        SMALL_ALPHA_VRACHY: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_VRACHY,
        SMALL_ALPHA_MACRON: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_MACRON,
        SMALL_ALPHA_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ALPHA_PERISPOMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_ALPHA_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ALPHA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        CAPITAL_ALPHA_VRACHY: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_VRACHY,
        CAPITAL_ALPHA_MACRON: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_MACRON,
        CAPITAL_ALPHA_VARIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_ALPHA_OXIA: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ALPHA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ALPHA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        SMALL_ETA_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_ETA_PERISPOMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_ETA_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_ETA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        CAPITAL_EPSILON_VARIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_EPSILON_OXIA: GreekAlphabet.UPPER_EPSILON + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ETA_VARIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_ETA_OXIA: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_ETA_PROSGEGRAMMENI: GreekAlphabet.UPPER_ETA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        SMALL_IOTA_VRACHY: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_VRACHY,
        SMALL_IOTA_MACRON: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_MACRON,
        SMALL_IOTA_DIALYTIKA_VARIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_VARIA,
        SMALL_IOTA_DIALYTIKA_OXIA: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_OXIA,
        SMALL_IOTA_PERISPOMENI: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_IOTA_DIALYTIKA_PERISPOMENI: GreekAlphabet.LOWER_IOTA + GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_IOTA_VRACHY: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_VRACHY,
        CAPITAL_IOTA_MACRON: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_MACRON,
        CAPITAL_IOTA_VARIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_IOTA_OXIA: GreekAlphabet.UPPER_IOTA + GreekDiacritic.COMBINING_OXIA,
        SMALL_UPSILON_VRACHY: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_VRACHY,
        SMALL_UPSILON_MACRON: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_MACRON,
        SMALL_UPSILON_DIALYTIKA_VARIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_VARIA,
        SMALL_UPSILON_DIALYTIKA_OXIA: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_OXIA,
        SMALL_RHO_PSILI: GreekAlphabet.LOWER_RHO + GreekDiacritic.COMBINING_PSILI,
        SMALL_RHO_DASIA: GreekAlphabet.LOWER_RHO + GreekDiacritic.COMBINING_DASIA,
        SMALL_UPSILON_PERISPOMENI: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_UPSILON_DIALYTIKA_PERISPOMENI: GreekAlphabet.LOWER_UPSILON + GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_PERISPOMENI,
        CAPITAL_UPSILON_VRACHY: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_VRACHY,
        CAPITAL_UPSILON_MACRON: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_MACRON,
        CAPITAL_UPSILON_VARIA: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_UPSILON_OXIA: GreekAlphabet.UPPER_UPSILON + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_RHO_DASIA: GreekAlphabet.UPPER_RHO + GreekDiacritic.COMBINING_DASIA,
        SMALL_OMEGA_VARIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_VARIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_OXIA_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_OXIA + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        SMALL_OMEGA_PERISPOMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PERISPOMENI,
        SMALL_OMEGA_PERISPOMENI_YPOGEGRAMMENI: GreekAlphabet.LOWER_OMEGA + GreekDiacritic.COMBINING_PERISPOMENI + GreekDiacritic.COMBINING_YPOGEGRAMMENI,
        CAPITAL_OMICRON_VARIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_OMICRON_OXIA: GreekAlphabet.UPPER_OMICRON + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_OMEGA_VARIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_VARIA,
        CAPITAL_OMEGA_OXIA: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_OXIA,
        CAPITAL_OMEGA_PROSGEGRAMMENI: GreekAlphabet.UPPER_OMEGA + GreekDiacritic.COMBINING_PROSGEGRAMMENI,
    }

    LETTERS = frozenset(EXPANDABLE_LETTERS.keys())

    EXPANDABLE_DIACRITICS = {
        PROSGEGRAMMENI: GreekDiacritic.COMBINING_PROSGEGRAMMENI,
        DIALYTIKA_PERISPOMENI: GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_PERISPOMENI,
        PSILI_VARIA: GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_VARIA,
        PSILI_OXIA: GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_OXIA,
        PSILI_PERISPOMENI: GreekDiacritic.COMBINING_PSILI + GreekDiacritic.COMBINING_PERISPOMENI,
        DASIA_VARIA: GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_VARIA,
        DASIA_OXIA: GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_OXIA,
        DASIA_PERISPOMENI: GreekDiacritic.COMBINING_DASIA + GreekDiacritic.COMBINING_PERISPOMENI,
        DIALYTIKA_VARIA: GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_VARIA,
        DIALYTIKA_OXIA: GreekDiacritic.COMBINING_DIALYTIKA + GreekDiacritic.COMBINING_OXIA,
        VARIA: GreekDiacritic.COMBINING_VARIA,
        OXIA: GreekDiacritic.COMBINING_OXIA,
        KORONIS: GreekDiacritic.COMBINING_KORONIS,
        PSILI: GreekDiacritic.COMBINING_PSILI,
        PERISPOMENI: GreekDiacritic.COMBINING_PERISPOMENI,
        DASIA: GreekDiacritic.COMBINING_DASIA,
    }

    DIACRITICS = frozenset(EXPANDABLE_DIACRITICS.keys())
