#
# Copyright (c) 2024 by Kristoffer Paulsson <kristoffer.paulsson@talenten.se>.
#
# Permission to use, copy, modify, and/or distribute this software for any purpose with
# or without fee is hereby granted, provided that the above copyright notice and this
# permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO
# THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
# IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#     https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
#
# Contributors:
#     Kristoffer Paulsson - initial implementation
#
"""All legal or valid glyphs for printing and using instead of duplicates."""
from greektextify.text.alphabet import GreekAlphabet
from greektextify.text.diacritic import GreekDiacritic
from greektextify.text.glyph import GreekGlyph
from greektextify.text.midway import GreekMidway

CUSTOM_GLYPHS = [
    (GreekGlyph(ch=GreekAlphabet.HYPHEN_MINUS, psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), GreekAlphabet.HYPHEN_MINUS),
    (GreekGlyph(ch=GreekMidway.APOSTROPHE, psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), GreekMidway.APOSTROPHE),
    (GreekGlyph(ch=GreekDiacritic.DEBUG_CIRCLE, psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), GreekDiacritic.DEBUG_CIRCLE),
]

All_VALID_GLYPHS = [
    (GreekGlyph(ch='Α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0391'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b1'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=True), '\u1fb1'),
    (GreekGlyph(ch='Α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=True), '\u1fb9'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=True, macron=False), '\u1fb0'),
    (GreekGlyph(ch='Α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=True, macron=False), '\u1fb8'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fb6'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f71'),
    (GreekGlyph(ch='Α', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fbb'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f70'),
    (GreekGlyph(ch='Α', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fba'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fb3'),
    (GreekGlyph(ch='Α', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fbc'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fb7'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fb4'),
    (GreekGlyph(ch='α', psili=False, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fb2'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f01'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f09'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f07'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f0f'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f05'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f0d'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f03'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f0b'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f81'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f89'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f87'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f8f'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f85'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f8d'),
    (GreekGlyph(ch='α', psili=False, dasia=True, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f83'),
    (GreekGlyph(ch='Α', psili=False, dasia=True, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f8b'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f00'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f08'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f06'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f0e'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f04'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f0c'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f02'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f0a'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f80'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f88'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f86'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f8e'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f84'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f8c'),
    (GreekGlyph(ch='α', psili=True, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f82'),
    (GreekGlyph(ch='Α', psili=True, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f8a'),
    (GreekGlyph(ch='Β', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0392'),
    (GreekGlyph(ch='β', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b2'),
    (GreekGlyph(ch='Γ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0393'),
    (GreekGlyph(ch='γ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b3'),
    (GreekGlyph(ch='Δ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0394'),
    (GreekGlyph(ch='δ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b4'),
    (GreekGlyph(ch='Ε', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0395'),
    (GreekGlyph(ch='ε', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b5'),
    (GreekGlyph(ch='ε', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f73'),
    (GreekGlyph(ch='Ε', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fc9'),
    (GreekGlyph(ch='ε', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f72'),
    (GreekGlyph(ch='Ε', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fc8'),
    (GreekGlyph(ch='ε', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f11'),
    (GreekGlyph(ch='Ε', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f19'),
    (GreekGlyph(ch='ε', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f15'),
    (GreekGlyph(ch='Ε', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f1d'),
    (GreekGlyph(ch='ε', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f13'),
    (GreekGlyph(ch='Ε', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f1b'),
    (GreekGlyph(ch='ε', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f10'),
    (GreekGlyph(ch='Ε', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f18'),
    (GreekGlyph(ch='ε', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f14'),
    (GreekGlyph(ch='Ε', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f1c'),
    (GreekGlyph(ch='ε', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f12'),
    (GreekGlyph(ch='Ε', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f1a'),
    (GreekGlyph(ch='Ϝ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03dc'),
    (GreekGlyph(ch='ϝ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03dd'),
    (GreekGlyph(ch='Ζ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0396'),
    (GreekGlyph(ch='ζ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b6'),
    (GreekGlyph(ch='Η', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0397'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b7'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fc6'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f75'),
    (GreekGlyph(ch='Η', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fcb'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f74'),
    (GreekGlyph(ch='Η', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fca'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fc3'),
    (GreekGlyph(ch='Η', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fcc'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fc7'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fc4'),
    (GreekGlyph(ch='η', psili=False, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fc2'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f21'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f29'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f27'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f2f'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f25'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f2d'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f23'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f2b'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f91'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f99'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f97'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f9f'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f95'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f9d'),
    (GreekGlyph(ch='η', psili=False, dasia=True, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f93'),
    (GreekGlyph(ch='Η', psili=False, dasia=True, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f9b'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f20'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f28'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f26'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f2e'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f24'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f2c'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f22'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f2a'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f90'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f98'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f96'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f9e'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f94'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f9c'),
    (GreekGlyph(ch='η', psili=True, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f92'),
    (GreekGlyph(ch='Η', psili=True, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f9a'),
    (GreekGlyph(ch='Θ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0398'),
    (GreekGlyph(ch='θ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b8'),
    (GreekGlyph(ch='Ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u0399'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03b9'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=True), '\u1fd1'),
    (GreekGlyph(ch='Ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=True), '\u1fd9'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=True, macron=False), '\u1fd0'),
    (GreekGlyph(ch='Ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=True, macron=False), '\u1fd8'),
    (GreekGlyph(ch='Ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u03aa'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u03ca'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fd6'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=True, vrachy=False, macron=False), '\u1fd7'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f77'),
    (GreekGlyph(ch='Ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fdb'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u1fd3'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f76'),
    (GreekGlyph(ch='Ι', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fda'),
    (GreekGlyph(ch='ι', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u1fd2'),
    (GreekGlyph(ch='ι', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f31'),
    (GreekGlyph(ch='Ι', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f39'),
    (GreekGlyph(ch='ι', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f37'),
    (GreekGlyph(ch='Ι', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f3f'),
    (GreekGlyph(ch='ι', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f35'),
    (GreekGlyph(ch='Ι', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f3d'),
    (GreekGlyph(ch='ι', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f33'),
    (GreekGlyph(ch='Ι', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f3b'),
    (GreekGlyph(ch='ι', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f30'),
    (GreekGlyph(ch='Ι', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f38'),
    (GreekGlyph(ch='ι', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f36'),
    (GreekGlyph(ch='Ι', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f3e'),
    (GreekGlyph(ch='ι', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f34'),
    (GreekGlyph(ch='Ι', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f3c'),
    (GreekGlyph(ch='ι', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f32'),
    (GreekGlyph(ch='Ι', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f3a'),
    (GreekGlyph(ch='Κ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u039a'),
    (GreekGlyph(ch='κ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03ba'),
    (GreekGlyph(ch='Λ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u039b'),
    (GreekGlyph(ch='λ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03bb'),
    (GreekGlyph(ch='Μ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u039c'),
    (GreekGlyph(ch='μ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03bc'),
    (GreekGlyph(ch='Ν', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u039d'),
    (GreekGlyph(ch='ν', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03bd'),
    (GreekGlyph(ch='Ξ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u039e'),
    (GreekGlyph(ch='ξ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03be'),
    (GreekGlyph(ch='Ο', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u039f'),
    (GreekGlyph(ch='ο', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03bf'),
    (GreekGlyph(ch='ο', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f79'),
    (GreekGlyph(ch='Ο', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ff9'),
    (GreekGlyph(ch='ο', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f78'),
    (GreekGlyph(ch='Ο', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ff8'),
    (GreekGlyph(ch='ο', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f41'),
    (GreekGlyph(ch='Ο', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f49'),
    (GreekGlyph(ch='ο', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f45'),
    (GreekGlyph(ch='Ο', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f4d'),
    (GreekGlyph(ch='ο', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f43'),
    (GreekGlyph(ch='Ο', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f4b'),
    (GreekGlyph(ch='ο', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f40'),
    (GreekGlyph(ch='Ο', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f48'),
    (GreekGlyph(ch='ο', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f44'),
    (GreekGlyph(ch='Ο', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f4c'),
    (GreekGlyph(ch='ο', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f42'),
    (GreekGlyph(ch='Ο', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f4a'),
    (GreekGlyph(ch='Π', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a0'),
    (GreekGlyph(ch='π', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c0'),
    (GreekGlyph(ch='Ρ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a1'),
    (GreekGlyph(ch='ρ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c1'),
    (GreekGlyph(ch='ρ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fe5'),
    (GreekGlyph(ch='Ρ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fec'),
    (GreekGlyph(ch='ρ', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fe4'),
    (GreekGlyph(ch='Σ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a3'),
    (GreekGlyph(ch='ς', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c2'),
    (GreekGlyph(ch='σ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c3'),
    (GreekGlyph(ch='Τ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a4'),
    (GreekGlyph(ch='τ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c4'),
    (GreekGlyph(ch='Υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a5'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c5'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=True), '\u1fe1'),
    (GreekGlyph(ch='Υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=True), '\u1fe9'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=True, macron=False), '\u1fe0'),
    (GreekGlyph(ch='Υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=True, macron=False), '\u1fe8'),
    (GreekGlyph(ch='Υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u03ab'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u03cb'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fe6'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=True, vrachy=False, macron=False), '\u1fe7'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f7b'),
    (GreekGlyph(ch='Υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1feb'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u1fe3'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f7a'),
    (GreekGlyph(ch='Υ', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fea'),
    (GreekGlyph(ch='υ', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=True, vrachy=False, macron=False), '\u1fe2'),
    (GreekGlyph(ch='υ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f51'),
    (GreekGlyph(ch='Υ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f59'),
    (GreekGlyph(ch='υ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f57'),
    (GreekGlyph(ch='Υ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f5f'),
    (GreekGlyph(ch='υ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f55'),
    (GreekGlyph(ch='Υ', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f5d'),
    (GreekGlyph(ch='υ', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f53'),
    (GreekGlyph(ch='Υ', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f5b'),
    (GreekGlyph(ch='υ', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f50'),
    (GreekGlyph(ch='υ', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f56'),
    (GreekGlyph(ch='υ', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f54'),
    (GreekGlyph(ch='υ', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f52'),
    (GreekGlyph(ch='Φ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a6'),
    (GreekGlyph(ch='φ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c6'),
    (GreekGlyph(ch='Χ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a7'),
    (GreekGlyph(ch='χ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c7'),
    (GreekGlyph(ch='Ψ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a8'),
    (GreekGlyph(ch='ψ', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c8'),
    (GreekGlyph(ch='Ω', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03a9'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u03c9'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1ff6'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f7d'),
    (GreekGlyph(ch='Ω', psili=False, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ffb'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f7c'),
    (GreekGlyph(ch='Ω', psili=False, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ffa'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ff3'),
    (GreekGlyph(ch='Ω', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ffc'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1ff7'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ff4'),
    (GreekGlyph(ch='ω', psili=False, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1ff2'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f61'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f69'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f67'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f6f'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f65'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f6d'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f63'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f6b'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa1'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa9'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fa7'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1faf'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa5'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fad'),
    (GreekGlyph(ch='ω', psili=False, dasia=True, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa3'),
    (GreekGlyph(ch='Ω', psili=False, dasia=True, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fab'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f60'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f68'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f66'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1f6e'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f64'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=False, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f6c'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f62'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=False, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1f6a'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa0'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa8'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fa6'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=False, perispomeni=True,
                dialytika=False, vrachy=False, macron=False), '\u1fae'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa4'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=True, varia=False, oxia=True, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fac'),
    (GreekGlyph(ch='ω', psili=True, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1fa2'),
    (GreekGlyph(ch='Ω', psili=True, dasia=False, ypogegrammeni=True, varia=True, oxia=False, perispomeni=False,
                dialytika=False, vrachy=False, macron=False), '\u1faa'),
]
